# Generated by Django 4.1.7 on 2023-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
